In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
# Assign colum names to the dataset
names = [' sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

dataset = pd.read_csv('iris.csv')

In [30]:
dataset.columns = names

In [31]:
dataset

sepal-length  sepal-width  petal-length  petal-width      Class
0              5.1          3.5           1.4          0.2     setosa
1              4.9          3.0           1.4          0.2     setosa
2              4.7          3.2           1.3          0.2     setosa
3              4.6          3.1           1.5          0.2     setosa
4              5.0          3.6           1.4          0.2     setosa
..             ...          ...           ...          ...        ...
145            6.7          3.0           5.2          2.3  virginica
146            6.3          2.5           5.0          1.9  virginica
147            6.5          3.0           5.2          2.0  virginica
148            6.2          3.4           5.4          2.3  virginica
149            5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [33]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,4].values

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2) 

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [37]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [39]:
y_pred = classifier.predict(x_test)

In [40]:
y_pred

array(['virginica', 'virginica', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'virginica', 'virginica', 'versicolor', 'virginica'],
      dtype=object)

In [41]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.88      0.78      0.82         9
   virginica       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30

[[12  0  0]
 [ 0  7  2]
 [ 0  1  8]]
